-- SEED BAPTÊME - 20 produits (best-sellers Etsy 8.2k ventes, bougies, dragées, magnets)
-- Basé recherche web: bougies personnalisées, dragées, magnets, fioles fleurs séchées

INSERT OR IGNORE INTO products(sku, slug, name, short_desc, long_desc, price_ht, price_ttc, cost_price, stock_qty, event_type, is_featured) VALUES
('BAP-BOUGIE-300', 'bougie-personnalisee-bapteme-verre-ambre-70g', 'Bougie Personnalisée Baptême Verre Ambré 70g', 'Bougie soja 70g personnalisée', 'Bougie soja 70g en verre ambré + étiquette personnalisée prénom date symbole religieux. Fabriquée main atelier, cire végétale. Best-seller baptême. 4-10€.', 5.75, 6.90, 2, 80, 'bapteme', 1),
('BAP-DRAGEE-301', 'contenant-dragees-bapteme-plexi-lot-20', 'Contenants Dragées Baptême Plexi Lot 20', 'Boîtes plexi transparent + ruban lot 20', 'Boîtes plexi transparent 5x5cm + ruban satin + étiquette personnalisée prénom date. Pour dragées. Best-seller.', 14.08, 16.90, 5, 50, 'bapteme', 1),
('BAP-MAGNET-302', 'magnets-bapteme-personnalises-lot-15', 'Magnets Baptême Personnalisés Lot 15', 'Magnets 5cm photo prénom lot 15', 'Magnets 5cm avec photo bébé + prénom date. Personnalisables. Les invités conservent sur frigo. Best-seller.', 16.58, 19.90, 6, 40, 'bapteme', 1),
('BAP-FIOLE-303', 'fiole-verre-fleurs-sechees-bapteme-lot-15', 'Fiole Verre Fleurs Séchées Baptême Lot 15', 'Fiole 10ml fleurs séchées lot 15', 'Fiole verre 10ml avec fleurs séchées + étiquette personnalisée. Se conserve très longtemps, déco maison invités. Élégant.', 20.75, 24.90, 8, 30, 'bapteme', 1),
('BAP-POCHON-304', 'pochons-dragees-bapteme-tissu-lot-20', 'Pochons Dragées Baptême Tissu Lot 20', 'Pochons lin + étiquette lot 20', 'Pochons lin naturel 8x10cm + étiquette personnalisée. Pour dragées. Réutilisable.', 12.42, 14.90, 4.5, 50, 'bapteme', 0),
('BAP-BONBONNIERE-305', 'bonbonniere-verre-bapteme-avec-etiquette', 'Bonbonnière Verre Baptême + Étiquette', 'Bonbonnière verre 8cm + étiquette', 'Bonbonnière verre 8cm avec couvercle + étiquette autocollante personnalisable. À remplir de sucreries.', 4.08, 4.90, 1.2, 60, 'bapteme', 0),
('BAP-BADGE-306', 'badges-bapteme-personnalises-lot-20', 'Badges Baptême Personnalisés Lot 20', 'Badges 5.6cm photo prénom lot 20', 'Badges 5.6cm avec photo + prénom. Peut se joindre à pochons. Couleurs fille/garçon.', 12.42, 14.90, 4, 40, 'bapteme', 0),
('BAP-SAVON-307', 'savons-bapteme-personnalises-lot-15', 'Savons Baptême Personnalisés Lot 15', 'Savons 30g + étiquette lot 15', 'Savons artisanaux 30g + étiquette personnalisée. Utile et raffiné.', 16.58, 19.90, 6, 35, 'bapteme', 0),
('BAP-BOUGIE-OURS-308', 'bougie-ourson-bapteme-lot-10', 'Bougie Ourson Baptême Lot 10', 'Mini bougies ourson lot 10', 'Mini bougies en forme ourson + étiquette. Format ludique pour enfants.', 20.75, 24.90, 8, 25, 'bapteme', 0),
('BAP-KIT-COLOR-309', 'kit-coloriage-bapteme-personnalise-lot-10', 'Kit Coloriage Baptême Personnalisé Lot 10', 'Étui carton + 6 crayons + taille-crayon lot 10', 'Kit complet: étui cylindrique carton naturel + taille-crayon intégré + 6 crayons. Pour enfants invités.', 24.08, 28.90, 10, 20, 'bapteme', 0),
('BAP-CIERGE-310', 'cierge-bapteme-blanc-25cm', 'Cierge Baptême Blanc 25cm', 'Cierge blanc personnalisable', 'Cierge baptême blanc 25cm, personnalisable prénom date. Traditionnel.', 6.25, 7.50, 2.2, 40, 'bapteme', 0),
('BAP-CADRE-311', 'cadre-bapteme-personnalise-bois', 'Cadre Baptême Personnalisé Bois', 'Cadre bois prénom date', 'Cadre bois clair 20x20cm avec prénom date + symbole. Souvenir.', 14.08, 16.90, 5, 20, 'bapteme', 0),
('BAP-AFFICHE-312', 'affiche-bapteme-personnalisee-prenom-date', 'Affiche Baptême Personnalisée Prénom Date', 'Affiche A4 prénom date poids', 'Affiche A4 personnalisée avec prénom, date, poids, taille, heure. Design épuré.', 10.75, 12.90, 3.5, 30, 'bapteme', 0),
('BAP-BOITE-SOUV-313', 'boite-souvenirs-bapteme-bois', 'Boîte Souvenirs Baptême Bois', 'Boîte bois avec compartiments', 'Boîte bois 20x15cm avec compartiments pour souvenirs baptême: bougie, médaille, etc.', 19.08, 22.90, 7, 15, 'bapteme', 0),
('BAP-MEDAILLE-314', 'medaille-bapteme-ange', 'Médaille Baptême Ange', 'Médaille ange or/argent', 'Médaille ange or ou argent, traditionnelle, pour parrain marraine.', 24.08, 28.90, 10, 15, 'bapteme', 0),
('BAP-COFFRET-315', 'coffret-bapteme-parrain-marraine', 'Coffret Baptême Parrain Marraine', 'Coffret bougie + cadre + carte', 'Coffret cadeau parrain marraine: bougie + cadre + carte demande.', 29.08, 34.90, 12, 15, 'bapteme', 1),
('BAP-ETIQUETTE-316', 'etiquettes-bapteme-personnalisees-lot-30', 'Étiquettes Baptême Personnalisées Lot 30', 'Étiquettes autocollantes lot 30', 'Étiquettes autocollantes rondes 4cm personnalisées prénom date, pour contenants.', 8.25, 9.90, 2.5, 60, 'bapteme', 0),
('BAP-GUIRLANDE-317', 'guirlande-bapteme-prenom-bois', 'Guirlande Baptême Prénom Bois', 'Guirlande lettres bois prénom', 'Guirlande lettres bois avec prénom bébé, 1.5m.', 16.58, 19.90, 6, 20, 'bapteme', 0),
('BAP-SACHET-GRAINES-318', 'sachet-graines-bapteme-personnalise-lot-20', 'Sachet Graines Baptême Personnalisé Lot 20', 'Sachet graines fleurs + étiquette lot 20', 'Sachet graines fleurs symbolisant vie et croissance + étiquette personnalisée. Idée originale éco.', 12.42, 14.90, 4, 40, 'bapteme', 0),
('BAP-TIMBALE-319', 'timbale-bapteme-personnalisee-argent', 'Timbale Baptême Personnalisée Argent', 'Timbale argent gravée', 'Timbale argent massif ou plaqué, gravée prénom date. Traditionnelle, 49-190€.', 41.58, 49.90, 18, 10, 'bapteme', 0);
